### ISSUE TITLE
Works on Mac?

### ISSUE THREAD

**Issue by cerkut** [spatUV/SART3Dmaster#1]
Hi, this toolbox sounds brilliant, congratulations. I am trying to tweak it to work on Mac. Do you think it will be possible? While dsp.AudioFileReader works with native CoreAudio drivers on Mac, I could not get any sound from SART3Dmaster yet. Currently I am backtracking the audio path in the toolbox related/specific to Asio4All drivers, if you have suggestions I'd had easier time in backtracking. Regards, Cumhur

**Comment by spatUV** [comment]
Hi Cumhur, thank you!

The way SART3D manages the reading and playback of audio streams relies completely on Mathwork's DSP System Toolbox. There are not any Asio4All specifics involved, providing the user the freedom to work with any ASIO driver. According to Mathworks' documentation (http://es.mathworks.com/hardware-support/audio-dst.html) DSP System supports CoreAudio, so adapting SART3D to work in Mac should be possible.

Audio reading/playback is initialized by the main playback function "tbPlayOnCallback" in SART3D.m. Try to explore a little bit the creation of the audioreader objects (and make sure that you tick some checkboxes corresponding to some virtual sources in the GUI in order to get some sound).

Best regards.

**Comment by cerkut** [comment]
Marking solved
